[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/api/now-playing"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
